### ISSUE TITLE
The results from the detection : Mirror side

### ISSUE THREAD

**Issue by japer21** [csharpseattle/tensorflowiOS#9]
I have some issues with the orientation. It seems like it inverts the detections_boxes, their coordinates,  so that the results are shown like in the mirror...

**Comment by japer21** [comment]
@csharpseattle 
I have succeeded to run the application within my own model. But when it comes to the detection part, it does detect the objects within the labels, but the rectangles are always put on the objects like in a mirror effect.


![image](https://user-images.githubusercontent.com/17979719/42502197-b045d112-8435-11e8-9266-4a93888a9a16.png)



figure1 is the order of objects we see on the real time camera streaming;
figure2 gives the detection boxes that are placed within the labels but the placing is not correct.

Did you come to result like this?
Thanks

**Comment by japer21** [comment]
@csharpseattle

**Comment by csharpseattle** [comment]
Hi @japer21 ,

Glad to hear you got it running.  Yes, there is a rotation bug.  Detection boxes are only correct in one of the landscape orientations.  I believe it is Landscape Left.  I am working on a fix now.  The fix is to rotate the pixel buffer as the pixel data is copied from the CVPixelBuffer into the TF Tensor.

**Comment by japer21** [comment]
@csharpseattle Thank you for your reply, it does mean so much to me. I am really trying hard to make it work, because I think the original frame as an input, is going through some modification, let's say some rotation, because even in the default orientation, Landscape Left, it does give the same result, like some kind of mirror effect, which I explained above. 
So this means, that what I think, is that each frame is rotated for 180 degrees and then proceeded so that when we get back the results, `detection_boxes` they detect the object but with different label.
So what I am trying to do, is to do a rotation:

```
//
    // Retain the pixel buffer, copy and make a CGImage out of it.
    //
    CFRetain(pixelBuffer);
    CVPixelBufferLockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
    CGImageRef cgImage = [self copyPixelBuffer:pixelBuffer];
    UIImage *uiImage = [[UIImage alloc] initWithCGImage:cgImage];
    
    UIImage *image2 = [self imageRotatedByDegrees:uiImage deg:180];
    UIImageWriteToSavedPhotosAlbum(image2, nil, nil, nil);
    if (orientation == UIDeviceOrientationLandscapeRight)
    {
        NSLog(@".........device oriented right");
    }else if (orientation == UIDeviceOrientationLandscapeLeft){
        NSLog(@".........device oriented left");
    }
    //UIImageOrientation imgOrientation = uiImage.imageOrientation;
    CFRelease(pixelBuffer);
    CVPixelBufferUnlockBaseAddress(pixelBuffer, 0);

```
It is in the `TensorflowGraph.mm` file, in the function `- (void)runModelOnPixelBuffer:(CVPixelBufferRef) pixelBuffer orientation: (UIDeviceOrientation) orientation;`.
And I will set up this image rotated as input so I will see what will happen. I have tried lot of things, although I am not so experienced in iOS programming/Objectiove-C, but maybe there must be also some configuration with the camera mode, I really do not know, but I need this so much.

Thanks

**Comment by csharpseattle** [comment]
I believe replacing the `copyPixelBuffer` function with the following code fixes issues with Landscape detection boxes but I'm still trouble shooting the portrait orientations.  You will also need to remove the  two special treatments to UIDeviceOrientationLandscapeRight in `runModelOnPixelBuffer`.

`- (CGImageRef) copyPixelBuffer: (CVImageBufferRef) pixelBuffer orientation: (UIDeviceOrientation) orientation
{
    //
    // alloc a CIImage with the pixel buffer.
    //
    CIImage* ciImage = [[CIImage alloc] initWithCVPixelBuffer:pixelBuffer];
    
    const int pixelBufHeight   = (int) CVPixelBufferGetHeight(pixelBuffer);
    const int pixelBufWidth    = (int) CVPixelBufferGetWidth(pixelBuffer);
    CGAffineTransform transform = CGAffineTransformIdentity;
    transform = CGAffineTransformScale(transform, float(kGraphImageWidth)/pixelBufWidth, float(kGraphImageHeight)/pixelBufHeight);
    CGFloat angle = 0.0;
    switch (orientation)
    {
        case UIDeviceOrientationPortrait:
            angle = -M_PI_2;
            break;
        case UIDeviceOrientationPortraitUpsideDown:
            angle = M_PI_2;
            break;
        case UIDeviceOrientationLandscapeLeft:
            angle = 0.0;
            break;
        case UIDeviceOrientationLandscapeRight:
            angle = M_PI;
            break;
        case UIDeviceOrientationUnknown:
        case UIDeviceOrientationFaceUp:
        case UIDeviceOrientationFaceDown:
        default:
            break;
    }
    
    transform = CGAffineTransformRotate(transform, angle);
    CIImage* resized = [ciImage imageByApplyingTransform:transform];
    
    //
    // Create a cgImage from the frame pixels
    //
    CIContext *context = [CIContext contextWithOptions:nil];
    CGImageRef cgImage = [context createCGImage:resized fromRect:resized.extent];
    
    return cgImage;
}
`

**Comment by japer21** [comment]
@csharpseattle  Ok, do you plan to fix it by yourself? I really like the way you have developed this application for tensorflow detection purpose on ios. I hope there will be some modifications in your code soon and I hope that you will find the most adequate solution as soon as possible. Thanks, keep in touch.

**Comment by japer21** [comment]
@csharpseattle When talking about frames per second, what is the fps in this application and where it is possible to manage it? Thanks

**Comment by japer21** [comment]
@csharpseattle I have tested with your modified function, but it seems to be the same, the mirror effect is still there..

**Comment by japer21** [comment]
@csharpseattle 
![drawing](https://user-images.githubusercontent.com/17979719/42703487-102aabb8-86cd-11e8-8aff-c2a7d397f81c.png)

So it really makes a mirror effect when showing the results.

**Comment by csharpseattle** [comment]
Hi @japer21 ,
I just pushed some fixes for orientations.  Give them a try and let me know if they fix your issue. 
Thanks

**Comment by japer21** [comment]
Hello @csharpseattle . Thanks for your message. I will try it and I will let you know soon. 
Thanks

**Comment by japer21** [comment]
Hello @csharpseattle , I have a question for you about the screen view, is it possible to resize the camera view on the screen so that I can have a place for something else to do on the screen?

![b3776888-583f-417c-994c-5dc5ed533de6](https://user-images.githubusercontent.com/17979719/42936076-7d121fd6-8b4b-11e8-96ab-eb11b6a516d8.png)

**Comment by japer21** [comment]
@csharpseattle  Unfortunately, nothing has changed with your new version of the code. It's still that mirror effect, I think there is still an issue with the rotation that you are doing....

**Comment by csharpseattle** [comment]
Are you getting bounding boxes in Portrait orientations?

**Comment by japer21** [comment]
@csharpseattle Finally it works, I made some modifications, it was due to the orientation, and when it's in Portrait mode the bounding boxes are not drawn correctly on the screen, but at least the mirror effect is gone. 
When about the split of the screen, where should I do it, because I want to split the screen, not the entire screen to be dedicated to the camera but also to have another part where I can for example count and display the number of detections ?
Thank you very much in advance.

**Comment by csharpseattle** [comment]
Cool.  I only have 2 devices, a 6s and a 5s and bounding boxes seem to be working on both in all orientations. As for splitting the screen, feel free to fork the project and adjust the sizes of the UIViews in Main.storyboard.  There is a CameraPreview where the camera frames are drawn and a BoundingBoxView where the bounding boxes are drawn.

**Comment by japer21** [comment]
@csharpseattle Ok, thank you, I will try to resize the screen (the camera view) but are there somewhere in your code the dimensions of the sizes (width and height) ? Do the CameraPreview and BoundingBoxView have to be the same size and same positions? Thanks

**Comment by japer21** [comment]
@csharpseattle It's strange the global view on ipad 9.3 inch, I really do not know why, the camera preview is not on the whole screen...

**Comment by csharpseattle** [comment]
That is because the camera’s aspect ratio may be different from the screen’s aspect ratio.  The result is letterboxing.  

The easiest thing to do is to change the camera preview layer’s videoGravity property: 

self.videoPreviewLayer.videoGravity = AVLayerVideoGravity.resize


But this will result in stretching of the video frame.    I think the correct thing to do is to keep the letter boxing but adjust the size of the
Bounding box view to match the camera’s aspect ratio.  I’ll try and add some logic to do that.

**Comment by japer21** [comment]
@csharpseattle Ok, I would appreciate if you try to add some logic, cause as you said, in the letterboxing, even there where the bounding edges are black (no camera preview) the boxes are drawn if an object detected inside of the screen aspect. 
Otherwise, I have added another UIView, in my case it's CustomView, similar to BoundingBoxesView, but then I have encountered this problem where the bounding boxes are drawn but not on the objects that are detected, but a little bit to left:
![image](https://user-images.githubusercontent.com/17979719/43250597-0471a31c-90be-11e8-97b9-72628fd4fbd3.png)

I tried to draw it below how it seems now:
![cd7a02a4-7db4-46c1-be9e-ef9b272cb9a7](https://user-images.githubusercontent.com/17979719/43250851-99b3a59c-90be-11e8-8868-55dff73e3528.png)
